version: '3'
services:
    #PHP Service
    codebase_laravel_app:
        build:
            context: .
            dockerfile: app.docker
        container_name: codebase_laravel_app
        volumes:
            - ../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - codebase_laravel_network
        links:
            - codebase_laravel_mysql:db
        extra_hosts:
            - host.docker.internal:host-gateway

    #Nginx Service
    web_server:
        image: nginx:1.21.1
        container_name: codebase_laravel_web_server
        ports:
            - 8080:80
        volumes:
            - ../:/var/www
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
        networks:
            - codebase_laravel_network
        depends_on:
            - codebase_laravel_app

    # MySQL Service
    codebase_laravel_mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 33065:3306
        environment:
            MYSQL_DATABASE: codebase_laravel_db
            MYSQL_ROOT_PASSWORD: password
        networks:
            - codebase_laravel_network
        volumes:
            - codebase_laravel_mysql:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    minio:
        image: minio/minio:latest
        ports:
            - "8088:8088"
            - "8900:8900"
        volumes:
            - minio-store:/data
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        command: server /data --console-address :8900 --address :8088
        networks:
            - codebase_laravel_network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
            - "ingest.geoip.downloader.enabled=false"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - "9200:9200"
        networks:
            - codebase_laravel_network
        restart: on-failure
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536

    kibana:
        image: docker.elastic.co/kibana/kibana:7.16.2
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            - "xpack.security.authc.http.enabled=false"
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        networks:
            - codebase_laravel_network
#Docker Networks
networks:
    codebase_laravel_network:
        driver: bridge
volumes:
    codebase_laravel_mysql: { }
    minio-store:
    elasticsearch-data:
